package model;
// Generated 02-dic-2022 10:19:33 by Hibernate Tools 4.3.1



/**
 * ExamenesId generated by hbm2java
 */
public class ExamenesId  implements java.io.Serializable {


     private String ccodalu;
     private String ccodcurso;
     private short nnumexam;

    public ExamenesId() {
    }

    public ExamenesId(String ccodalu, String ccodcurso, short nnumexam) {
       this.ccodalu = ccodalu;
       this.ccodcurso = ccodcurso;
       this.nnumexam = nnumexam;
    }
   
    public String getCcodalu() {
        return this.ccodalu;
    }
    
    public void setCcodalu(String ccodalu) {
        this.ccodalu = ccodalu;
    }
    public String getCcodcurso() {
        return this.ccodcurso;
    }
    
    public void setCcodcurso(String ccodcurso) {
        this.ccodcurso = ccodcurso;
    }
    public short getNnumexam() {
        return this.nnumexam;
    }
    
    public void setNnumexam(short nnumexam) {
        this.nnumexam = nnumexam;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExamenesId) ) return false;
		 ExamenesId castOther = ( ExamenesId ) other; 
         
		 return ( (this.getCcodalu()==castOther.getCcodalu()) || ( this.getCcodalu()!=null && castOther.getCcodalu()!=null && this.getCcodalu().equals(castOther.getCcodalu()) ) )
 && ( (this.getCcodcurso()==castOther.getCcodcurso()) || ( this.getCcodcurso()!=null && castOther.getCcodcurso()!=null && this.getCcodcurso().equals(castOther.getCcodcurso()) ) )
 && (this.getNnumexam()==castOther.getNnumexam());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCcodalu() == null ? 0 : this.getCcodalu().hashCode() );
         result = 37 * result + ( getCcodcurso() == null ? 0 : this.getCcodcurso().hashCode() );
         result = 37 * result + this.getNnumexam();
         return result;
   }   


}


