package model;
// Generated 02-dic-2022 10:19:33 by Hibernate Tools 4.3.1



/**
 * MatriculasId generated by hbm2java
 */
public class MatriculasId  implements java.io.Serializable {


     private String ccodalu;
     private String ccodcurso;

    public MatriculasId() {
    }

    public MatriculasId(String ccodalu, String ccodcurso) {
       this.ccodalu = ccodalu;
       this.ccodcurso = ccodcurso;
    }
   
    public String getCcodalu() {
        return this.ccodalu;
    }
    
    public void setCcodalu(String ccodalu) {
        this.ccodalu = ccodalu;
    }
    public String getCcodcurso() {
        return this.ccodcurso;
    }
    
    public void setCcodcurso(String ccodcurso) {
        this.ccodcurso = ccodcurso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculasId) ) return false;
		 MatriculasId castOther = ( MatriculasId ) other; 
         
		 return ( (this.getCcodalu()==castOther.getCcodalu()) || ( this.getCcodalu()!=null && castOther.getCcodalu()!=null && this.getCcodalu().equals(castOther.getCcodalu()) ) )
 && ( (this.getCcodcurso()==castOther.getCcodcurso()) || ( this.getCcodcurso()!=null && castOther.getCcodcurso()!=null && this.getCcodcurso().equals(castOther.getCcodcurso()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCcodalu() == null ? 0 : this.getCcodalu().hashCode() );
         result = 37 * result + ( getCcodcurso() == null ? 0 : this.getCcodcurso().hashCode() );
         return result;
   }   


}


